user: www-data
group: www-data
pid: tmp/pids/thin.pid
wait: 30
timeout: 30
log: log/thin.log
max_conns: 1024
rackup: config.ru
require: []
address: torianinmobile.pl
max_persistent_conns: 512
environment: production
daemonize: false
socket: /tmp/thin.sock
